[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Form handling configuration
[build.processing]
  skip_processing = false

[build.processing.forms]
  skip_processing = false

# Explicit form configuration
[[forms]]
  name = "help-contact"

[[forms]]
  name = "contact"

# Redirect rules
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Form notifications (optional)
# You can configure email notifications for form submissions
# [build.processing.forms]
#   skip_processing = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
